version: '3'

services:
  web:
    container_name: web
    build: ./docker
    ports:
      - 8080:80
    privileged: true
    volumes:
      - ./typing-app:/var/www/html

  db:
    image: mysql:8.0
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
